### ISSUE TITLE
Datadyne Extraction: Guard in the dark infinite shooting

### ISSUE THREAD

**Issue by Lebon14** [fgsfdsfgs/perfect_dark#17]
Yes, this can happen. It does not happen every time, however. I recorded a clip of it happening here:

https://www.youtube.com/watch?v=2M2Aldp25Yk

Sorry for no sound but it should be very obvious.

The guard should shoot a bit in the dark but not indefinitely. He'll stop when you shoot him.

EDIT: Got it to happen somewhere else. I think it's triggered when the guards try to shoot you pre-emptively.

**Comment by ghost** [comment]
This is caused by the animation for camping guards getting stuck, and also happens in GoldenEye at 60 FPS.
1964 GEPD has a fix for this, which should be looked into for reference.

**Comment by Graslu** [comment]
Yes 1964 GEPD has many fixes for things that break at 60FPS+, camping guards, slow motion, smart slow motion, etc...

**Comment by Lebon14** [comment]
any fix should be possible now, no?

**Comment by ghost** [comment]
This is fixed as of the recent actions. The camping guards in both Extraction and Deep Sea no longer get stuck.

**Comment by tmyqlfpir** [comment]
~~Still broken as of 1439f8bbebe6e23b5df2398f66a8f7d48e374758. https://github.com/fgsfdsfgs/perfect_dark/assets/80724828/caa06358-a4d4-4fed-8a9e-fdf1b6931b49~~

**Comment by Graslu** [comment]
That one is also always broken on 1964GEPD and I think even N64. At the time discussing it with Carnivorous we thought that maybe it was a 'tutorial' guard.

**Comment by tmyqlfpir** [comment]
After further testing I am able to confirm that it matches 1964GEPD's behavior, and that any other mission that includes camping guards do not pause indefinitely - which likely suggests they were meant to do that.

**Comment by fgsfdsfgs** [comment]
Closing this for now then.
