### ISSUE TITLE
Datadyne: Defection Carpet Texture Broken

### ISSUE THREAD

**Issue by xanshark** [fgsfdsfgs/perfect_dark#25]
Probably known, but there's no issue open, so I'm opening one for it. The carpet texture in Datadyne: Defection seems to be corrupted in some way, looks like when you decode a texture the wrong way in the GoldenEye Setup Editor. There could be more things affected in this way, I just haven't found them.

How it looks in the port:
![Datadyne Defection Floor Port](https://github.com/fgsfdsfgs/perfect_dark/assets/79879329/9cdb5fe3-9a3e-4540-8a69-e643f9f65e60)

How it looks normally, in 1964 GEPD Edition:
![Datadyne Defection Floor Emulator](https://github.com/fgsfdsfgs/perfect_dark/assets/79879329/c8de78c5-499e-44d0-9a2e-431b68ce9c16)

**Comment by ghost** [comment]
A similar issue happens in the exterior of Air base but this seems to be mip map related, since it changes with distance:
![air base mountains](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/df8fb740-3b99-435a-9eb0-6e7a011bb234)

Grid also has similar corrupted wall textures: 
<img width="640" alt="grid walls" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/5be96468-56ec-4e43-a978-10b4252e7946">

**Comment by fgsfdsfgs** [comment]
The last one might be a problem with texture decoding, the first two are most likely a problem with how mipmaps are handled. Which is to say, they aren't.

**Comment by Phnod** [comment]
A similar looking artifact as the last image above on Attack Ships's animated lights. In both cases I noticed it was possible to see through them, could be why they look so weird too if it's trying to decode them with transparency? Not sure.
![2023 08 18 T(17 15 49)pd_htEYhPEbCt](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/ecc8d423-921d-4fc6-91b8-fccb8b1f83cb)
![2023 08 18 T(16 51 23)pd_0gr1ZLhFxm](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/a897e438-e813-4fa6-bdf8-972baa6941a7)

**Comment by ghost** [comment]
![fixed textures](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/551b5cc3-bb7a-452e-9275-2e026d45bb5a)

Latest actions (as of writing this) fixed the animated texture error.

**Comment by fgsfdsfgs** [comment]
The carpet has also been fixed a while ago, though detail textures on it are still missing. See #101 for more texture-related issues.
