### ISSUE TITLE
Game crashes in cheat menu

### ISSUE THREAD

**Issue by toatahu116** [fgsfdsfgs/perfect_dark#641]
Specifically, whenever the mouse hovers over the last cheat in the gameplay section, the game freeze and crashes. cheat reported with pc 64 bit version

**Comment by fgsfdsfgs** [comment]
I can't reproduce this. What region are you using? Did you get the build from here or somewhere else? How old is the build?

**Comment by fgsfdsfgs** [comment]
Still can't reproduce this. If anyone is still getting this crash, please comment here with information I requested above.

**Comment by Rayman1103** [comment]
I just wanted to let you know that I am also crashing when navigating to the bottom Cheat option in the Gameplay section as toatahu116 described.

I am using the latest version of **x86_64-linux** from the Releases page here. I have it setup on my Steam Deck. Running the USA region rom.

I've also tested with **i686-linux** and it still crashes.

I setup the Transfer Pak as well if that could be related or not.

**Comment by fgsfdsfgs** [comment]
Aight, thanks for the report, I'll recheck it when I can.

**Comment by fgsfdsfgs** [comment]
Tried to reproduce this again on x86_64-linux. No dice. Maybe it was fixed by the recently merged cheat fix PR.

**Comment by Rayman1103** [comment]
I just updated the x86_64-linux version and tested again, it's sadly still crashing for me when selecting the very bottom Cheat option in the Gameplay menu.

Could it be an issue with hardware? Since toatahu116 stated they were on PC and experienced the crash.

Are there any crash dumps or log files that are generated anywhere that may help you in tracking down the issue?

**Comment by fgsfdsfgs** [comment]
It's supposed to show a crash window with some information and also generate a `pd.crash.log` in the working directory (which usually will be where you run the game from). If it doesn't, you can try running it under gdb like so:
```gdb ./pd.x86_64```
then type `r` and hit Enter. When it crashes, type `bt` and hit Enter, then paste the resulting output in here.

It's most likely not a hardware issue, but just me fucking something up in the cheat menu when the dual wield cheat was added.
