### ISSUE TITLE
Tranquilizer weapon causing crash

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#8]
In missions where there is an enemy that uses a tranquilizer or there is a psychosis gun in the world(Maian SOS) the game can crash. This may be two separate bugs but they both share a weapon model in common. In a recent [livestream](https://www.youtube.com/watch?v=griSpYrrvLI&t=8855s), Graslu00 implements a workaround by walking backwards into the psychosis gun to prevent it from appearing on screen, preventing the crash.

**Comment by fgsfdsfgs** [comment]
This might be at least partially related to a few texture-related bugs that have been fixed over the past 24 hours. Needs re-testing.

**Comment by megatog615** [comment]
I just tested. It still crashes. Testing this one is easy as the crash occurs immediately upon opening the first door in Maian SOS.

**Comment by fgsfdsfgs** [comment]
No longer crashes in Maian SOS after the last commit. Not sure about tranquilizer guns.

**Comment by Graslu** [comment]
Can confirm that both Psychosis and Tranquillizer guns no longer crash the game.
